# Generated by Django 3.2.3 on 2022-12-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20221202_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
