# Generated by Django 3.2.3 on 2022-12-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_properties_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimages',
            old_name='images',
            new_name='image',
        ),
    ]
