# Generated by Django 3.2.3 on 2022-12-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_images_propertyimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
