# Generated by Django 3.2.3 on 2022-12-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_isfeatured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
