# Generated by Django 3.2.3 on 2022-12-03 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_isfeatured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimages',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='belongs_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
