# Generated by Django 3.2.3 on 2022-12-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20221203_1347'),
        ('properties', '0011_remove_property_isfeatured'),
    ]

    operations = [
    ]
