# Generated by Django 3.2.3 on 2022-12-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_merge_20221203_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimages',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
    ]
