# Generated by Django 3.2.3 on 2022-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_isfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image6',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image7',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image8',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image9',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
