# Generated by Django 3.2.3 on 2022-12-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_auto_20221203_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image9',
        ),
    ]
