# Generated by Django 3.2.3 on 2022-12-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20221203_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image6',
        ),
    ]
